services:

  dogx-bct:
    image: dex-bctchain
    build: ./
    ports:
      - 3001:3000
    restart: always
    deploy:
        resources:
            limits:
              cpus: "2.0"
              memory: 8G
            reservations:
              cpus: "1.0"
              memory: 2G
              